-- MySQL Script generated by MySQL Workbench
-- Thu May 13 20:20:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nutritionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nutritionist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nutritionist` (
  `id_nutritionist` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `number_of_advice` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_nutritionist`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `numero_do_conselho_UNIQUE` (`number_of_advice` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `weight` DECIMAL NOT NULL,
  `height` DECIMAL NOT NULL,
  `objective` VARCHAR(50) NULL,
  PRIMARY KEY (`id_patient`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flat_feed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flat_feed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flat_feed` (
  `id_flat_feed` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATE NOT NULL,
  `date_finish` DATE NOT NULL,
  `objective` VARCHAR(100) NULL,
  `Nutritionist_id_nutritionist` INT NOT NULL,
  `patient_id_patient` INT NOT NULL,
  PRIMARY KEY (`id_flat_feed`),
  INDEX `fk_flat_feed_Nutritionist1_idx` (`Nutritionist_id_nutritionist` ASC) VISIBLE,
  INDEX `fk_flat_feed_patient1_idx` (`patient_id_patient` ASC) VISIBLE,
  CONSTRAINT `fk_flat_feed_Nutritionist1`
    FOREIGN KEY (`Nutritionist_id_nutritionist`)
    REFERENCES `mydb`.`Nutritionist` (`id_nutritionist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flat_feed_patient1`
    FOREIGN KEY (`patient_id_patient`)
    REFERENCES `mydb`.`patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`snack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`snack` ;

CREATE TABLE IF NOT EXISTS `mydb`.`snack` (
  `id_snack` INT NOT NULL AUTO_INCREMENT,
  `name_of_snack` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `flat_feed_id_flat_feed` INT NOT NULL,
  PRIMARY KEY (`id_snack`),
  INDEX `fk_snack_flat_feed1_idx` (`flat_feed_id_flat_feed` ASC) VISIBLE,
  CONSTRAINT `fk_snack_flat_feed1`
    FOREIGN KEY (`flat_feed_id_flat_feed`)
    REFERENCES `mydb`.`flat_feed` (`id_flat_feed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
